# Generated by Django 3.2.7 on 2021-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20211109_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
