# Generated by Django 3.2.7 on 2021-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
